//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendsMatrix.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbEntities : DbContext
    {
        public DbEntities()
            : base("name=DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Relation> Relations { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<GetFriendsLevels_Result> GetFriendsLevels(Nullable<int> level, Nullable<int> userID)
        {
            var levelParameter = level.HasValue ?
                new ObjectParameter("Level", level) :
                new ObjectParameter("Level", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFriendsLevels_Result>("GetFriendsLevels", levelParameter, userIDParameter);
        }
    
        public virtual ObjectResult<testProc_Result> testProc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<testProc_Result>("testProc");
        }
    }
}
